version: "3.9"
services:
  react:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
